### ISSUE TITLE
Headless example

### ISSUE THREAD

**Issue by ziflex** [paulrouget/servo-embedding-example#13]
Hi there,

First of all I would like to thank you for the project, it's very useful. 
As far as I know, ``glutin`` supports headless rendering. Could  you provide a simple example of how to set it up?

**Comment by ziflex** [comment]
Also,  is there a way to get an access to a DOM of currently open window like in CEF?

**Comment by paulrouget** [comment]
For headless, it's easier to just use `osmesa-sys`. An example can be found here: https://github.com/servo/servo/blob/master/ports/servo/glutin_app/window.rs#L66

> Also, is there a way to get an access to a DOM of currently open window like in CEF?

Not yet.

**Comment by ziflex** [comment]
Thank you!
Are there any plans regarding an access to DOM?

**Comment by paulrouget** [comment]
>  Are there any plans regarding an access to DOM?

It's been discussed before. People want it. I'm not sure yet how this will work.
