### ISSUE TITLE
Wrong positions for mouse event

### ISSUE THREAD

**Issue by antoyo** [paulrouget/servo-embedding-example#3]
Hi.
If I resize/move the window, the position of the mouse will not be good, i.e. the mouse needs to be below the link to highlight it.
Here's a screenshot:
![servo](https://user-images.githubusercontent.com/584972/30982483-81648066-a455-11e7-976c-270f882d4ff1.png)
I have the same issue in the gtk version and I'd like to know the fix.
Thanks to fix this issue.

**Comment by paulrouget** [comment]
This should fix it: e7f0c33. Resizing was not supported. Now the gl buffer is correctly repositioned.

**Comment by antoyo** [comment]
Thanks, the issue is now fixed.
