### ISSUE TITLE
Confising tutorial step

### ISSUE THREAD

**Issue by dkotrada** [paulrouget/servo-embedding-example#4]
Hi. I don't know how to do here: at this step https://github.com/paulrouget/servo-embedding-example#update-servo

I thought I did it here: whit this step https://github.com/paulrouget/servo-embedding-example#libservo

**Comment by paulrouget** [comment]
Hope this makes it easier to understand: https://github.com/paulrouget/servo-embedding-example/commit/7a21862f4145dec65be2175837fc7a33538a16ee

**Comment by dkotrada** [comment]
Ok. If I understood it right. Then the section (Update servo) of README.md no longer needed. Since I did it in previous section.  (libservo).


~~~
Update servo

In this example, we depend on a specific version of Servo. When you want to update Servo to a more recent version, do:

    change the revision in Cargo.toml (the rev field)
    Copy rust-toolchain, Cargo.log and resources from Servo
~~~

**Comment by paulrouget** [comment]
You only do that if ever want to update servo. As in, let's say, next month, you don't want to use a one month version of servo, you will have to go through these steps.

**Comment by paulrouget** [comment]
> Ok. If I understood it right. Then the section (Update servo) of README.md no longer needed. Since I did it in previous section. (libservo).

Yes.
